name: projectv2
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  google_maps_flutter: ^2.2.0
  provider: ^6.1.5
  geolocator: ^9.0.2
  url_launcher: ^6.0.20
  permission_handler: ^11.3.1
  easy_image_viewer: ^1.5.1
  google_fonts: ^6.2.1
  get: ^4.6.5
  http: 1.1.0
  path: ^1.8.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/images/hgt.png
    - assets/images/higertech.png


  uses-material-design: true


